language: php

php:
    - 7.3
    - 7.4
    - 8.0

before_script:
    - composer self-update
    - composer update --prefer-source --no-interaction --dev

script:
    - vendor/bin/phpunit

notifications:
    email: karol_dabrowski@interia.eu

cache:
    directories:
        - $HOME/.composer/cache/files
